# Generated by Django 5.2.1 on 2025-05-27 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Manufactured",
            new_name="Manufacturer",
        ),
    ]
