# Generated by Django 5.2.1 on 2025-05-27 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_rename_manufactured_manufacturer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="manufactured",
            new_name="manufacturer",
        ),
        migrations.AlterField(
            model_name="car",
            name="drivers",
            field=models.ManyToManyField(
                related_name="Cars", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
