# Generated by Django 5.2.1 on 2025-05-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0003_rename_manufactured_car_manufacturer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="email",
            field=models.EmailField(max_length=255),
        ),
    ]
